services:
  - type: web
    name: vtu-result-portal
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: CHROME_BIN
        value: /opt/render/project/.render/chrome/opt/google/chrome/chrome