services:
  - type: web
    name: vtu-result-portal
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    # Install Chrome via apt
    packages:
      - chromium
      - chromium-driver